### ISSUE TITLE
可以移植到单片机上吗

### ISSUE THREAD

**Issue by kekemuyu** [icexin/eggos#106]
其实是想用go语言开发嵌入式，单片机肯定用不上go的标准库。只要能用上go的协程、管道等主要特性就行。移植的难点估计主要是单片机不支持mmu，内存管理不知道怎么处理。

**Comment by icexin** [comment]
这个项目面向嵌入式arm，你可以看看。https://github.com/f-secure-foundry/tamago

**Comment by kekemuyu** [comment]
看了一下，支持的芯片都是带mmu的arm。而且正如你在知乎介绍的，他是修改了编译器的方案。我是喜欢你的方案的，使得能够实时跟进go的更新。带mmu的arm，eegos应该也可以移植上去。目前有两个支持单片机的go方案，一个是emgo，一个是tinygo。但都对go编译器做了大改动，而你的方案使得移植变得异常简单，只要能运行eggos即可。对eggos很感兴趣，接下来好好研究一下，感谢你的创新设计。

**Comment by icexin** [comment]
嗯，项目最开始是想用go编写一个内核，后来发现可以把eggos变成一个库，配合简单的命令行工具，开发者可以使用标准go编译器进行透明编译，从而让标准go程序运行在裸机上。非常感谢关注，有机会可以多交流沟通。
