### ISSUE TITLE
关于内核的疑问

### ISSUE THREAD

**Issue by kekemuyu** [icexin/eggos#107]
看了一下内核调度部分的代码，架构图中说这部分是没有go runtime的。但是这部分代码是go写的，编译后不就自动使用了go runtime吗？

**Comment by icexin** [comment]
内核调度的代码跟go runtime的代码很像，都不依赖runtime进行内存分配，并且也没有使用go的高级数据结构，比如map，channel等，另外函数的声明也避开了go的调度器插桩。总的来说，虽然是go代码，但没有依赖任何runtime的功能。

**Comment by kekemuyu** [comment]
@“函数的声明也避开了go的调度器插桩”
函数声明没发现特别之处，唯一不同是加了条件编译//go:nosplit是跳过栈溢出检测，还望大神赐教

**Comment by icexin** [comment]
一般函数的入口都被go编译器加入了一段代码，这段代码一方面用来进行栈的动态扩张，也用来进行抢占式调度。加入`go:nosplit`可以让编译器不再生成这段代码。这个技巧在go的runtime里面被大量使用，特别是当前运行的上下文没有一个合法的P。

**Comment by kekemuyu** [comment]
妙啊！是不是可以这样解释：go runtime肯定不能依赖自身运行，参考go  runtime的源码就能避免使用runtime

**Comment by icexin** [comment]
是的，eggos很多地方都参考了runtime的实现。

**Comment by icexin** [comment]
如果没有其他问题的话，我就关闭issue了，随时欢迎交流沟通。

**Comment by kekemuyu** [comment]
好的，有关内核的问题未来还会遇到，正在学习操作系统，正在看《一个操作系统的实现》。相关问题还会再这个标题下请教

**Comment by kekemuyu** [comment]
函数thread0调用go_entry()进入了go runtime, 然后程序如何往下运行呢？runtime直接调用了eggos的init()吗？
整个流程是boot->kernel->runtime->eggos->app, 好像和架构图对应起来了。

**Comment by icexin** [comment]
是这么回事，eggos的内核不归go runtime管理，相反为go runtime提供服务；eggos的用户空间其实就是一个普通的go程序，因此是构建在runtime之上的

**Comment by kekemuyu** [comment]
这个os很适合用在嵌入式上。嵌入式一直是c的天下，自从学了go，就想用go来开发。在性能较弱的arm(比如arm9,很多控制领域还是老架构)上跑个linux，显得太重了。eggos很轻量，嵌入式开发不需要go的完整库支持，有自带的特性就能让嵌入式开发如虎添翼。如果能支持cgo就更好了，嵌入式的外设应该还是c开发方便，然后封装成库。

**Comment by kekemuyu** [comment]
碰到个大问题，突然想起，go build不能直接编译汇编文件。看到kernel使用egg工具编译的，关于将go文件如何编译不嵌入runtime的二进制文件，大神能介绍一下吗？

**Comment by icexin** [comment]
go可以用汇编，不过是自己的汇编格式，你在官方文档上找一下

**Comment by kekemuyu** [comment]
plan9汇编了解一些。只是不指导如何编译，看到kernel的编译命令是“GOOS=linux GOARCH=386 go build -o kernel.elf  -ldflags '-E github.com/icexin/eggos/kernel.rt0 -T 0x100000'”。
于是尝试写了一个简单的arm版本例子：
rt0.s
`#include "textflag.h"
TEXT ·rt0(SB), NOSPLIT, $0-0
	RET`
add.go
`package add
//go:nosplit
func rt0()
//go:nosplit
func Add(a, b int) int {
	return a + b
}`
编译命令(go env 目标GOARCH=arm)：go build -o add.elf  -ldflags '-E rt0 -T 0x0'
编译是成功的，但是用arm-none-eabi-objdump -d add.elf反汇编提示：
In archive add.elf:
arm-none-eabi-objdump: __.PKGDEF: file format not recognized
arm-none-eabi-objdump: _go_.o: file format not recognized
arm-none-eabi-objdump: rt0.o: file format not recognized
应该是生成格式不对，另外我试过将一个带runtime的正常go程序编译成arm目标二进制，反汇编是可以的。不知道哪里出了问题

**Comment by kekemuyu** [comment]
plan9汇编了解一些。只是不知道如何编译，看到kernel的编译命令是“GOOS=linux GOARCH=386 go build -o kernel.elf  -ldflags '-E github.com/icexin/eggos/kernel.rt0 -T 0x100000'”。
于是尝试写了一个简单的arm版本例子：
rt0.s
```
#include "textflag.h"
TEXT ·rt0(SB), NOSPLIT, $0-0
	RET
```
add.go

```
package add
//go:nosplit
func rt0()
//go:nosplit
func Add(a, b int) int {
	return a + b
}
```

编译命令(go env 目标GOARCH=arm)：go build -o add.elf  -ldflags '-E rt0 -T 0x0'
编译是成功的，但是用arm-none-eabi-objdump -d add.elf反汇编提示：
In archive add.elf:
arm-none-eabi-objdump: __.PKGDEF: file format not recognized
arm-none-eabi-objdump: _go_.o: file format not recognized
arm-none-eabi-objdump: rt0.o: file format not recognized
应该是生成格式不对，另外我试过将一个带runtime的正常go程序编译成arm目标二进制，反汇编是可以的。不知道哪里出了问题

**Comment by kekemuyu** [comment]
我想简单了，想要得到elf目标文件，还要有main包，想要实现一个简单的裸机程序也并不容易，启动文件还是要设置好参数跳转到go 的runtime才行。

**Comment by icexin** [comment]
不用非要跳到go的runtime，可以看看kernel的preinit部分，是最后才跳到go runtime的，之前都不需要也可以正常写代码，可以用一个空的main函数让go编译器能生成elf。

**Comment by kekemuyu** [comment]
能不能运行先放一边，理论上是不是不用跳到preinit，编译也能成功。我把上面简单例子改了一下，编译出错如下：
```go
# _/home/iotbbs/arm/gotest
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
cmd/link/internal/ld.makePclntab(0xc000144000, 0xc000874000, 0x39b, 0x39b, 0xc00014e000, 0xc000038800, 0x0, 0xc000106c58, 0x44f6cc, 0xe6c, ...)
	/usr/local/go/src/cmd/link/internal/ld/pcln.go:78 +0x525
cmd/link/internal/ld.(*Link).pclntab(0xc000144000, 0xc000874000, 0x39b, 0x39b, 0xc)
	/usr/local/go/src/cmd/link/internal/ld/pcln.go:856 +0x67
cmd/link/internal/ld.Main(0x881440, 0x4, 0x8, 0x1, 0xd, 0xe, 0x0, 0x0, 0x6e4558, 0x12, ...)
	/usr/local/go/src/cmd/link/internal/ld/main.go:307 +0x11a5
main.main()
	/usr/local/go/src/cmd/link/main.go:68 +0x258
```

**Comment by icexin** [comment]
最终的符号表里面得有_rt0_amd64_linux类似的符号

**Comment by kekemuyu** [comment]
卡在生成elf了，加了_rt0_arm_linux也不行，可能是准备的参数不正确，eggos是x86架构没法参考，主要是这方面资料太少了，参考tamago，也是没有头绪，现在感觉像是无头苍蝇找不到蛋的入口。

**Comment by kekemuyu** [comment]
卡在生成elf了，加了_rt0_arm_linux也不行，可能是准备的参数不正确，eggos是x86架构没法参考，主要是这方面资料太少了，参考tamago，也是没有头绪，现在感觉像是无头苍蝇找不到蛋的入口。

**Comment by pedrogao** [comment]
之前我一直疑惑，go 如何逃逸掉 runtime 的限制，因为 go 的 runtime 是很重的，看到这里很受启发，希望作者能快点更新文档，https://eggos.icexin.com/docs/boot-loader/grub/ 如何最小化 runtime，很期待

**Comment by kekemuyu** [comment]
最近参考了tamago的源码，决定在它的基础上研究arm的最小runtime，从而移植eggos到arm。

**Comment by kekemuyu** [comment]
能不能运行放一边，终于可以编译成功了：
### rt0.s
```go
#include "textflag.h"

TEXT ·rt0(SB), NOSPLIT,$0
        // Detect HYP mode and switch to SVC if necessary
        WORD    $0xe10f0000     // mrs r0, CPSR
        AND     $0x1f, R0, R0   // get processor mode
	
	JMP _rt0_amd64_linux(SB)
```
### main.go
```go
package main

//go:nosplit
func rt0()

func main(){

}

```
### build.sh
```go
GO_EXTLINK_ENABLED=0 CGO_ENABLED=0 GOARM=5 GOARCH=arm go build -o add -ldflags '-E _rt0_arm_linux -T 0x80010000 -R 0x1000'
```

**Comment by kekemuyu** [comment]
终于可以生成elf了[https://whycan.com/files/members/1315/add_20220409-1201.zip](url)
