### ISSUE TITLE
Add support for GUI

### ISSUE THREAD

**Issue by icexin** [icexin/eggos#11]
Rely on the following work:

- [x] Mouse support
- [x] A GUI lib, eg [nuklear](https://github.com/vurtun/nuklear)
- [x] A render lib, eg [fauxgl](https://github.com/fogleman/fauxgl)

**Comment by nerososft** [comment]
https://github.com/SynestiaOS/SynestiaOS/releases/tag/V0.1.4

**Comment by icexin** [comment]
@nerososft Thanks!

My plan for the GUI is as follows:

1. The UI library

For the UI library part I plan to port nuklear to eggos, considering that most of the current implementations are based on cgo, but currently eggos does not support cgo, so I need a pure go version. cznic has already written a translator from c to go ([ccgo](https://gitlab.com/cznic/ccgo)). I tried it briefly and the final result was not bad. However, there is a slight problem with the libc part, which should not be difficult to solve.

2. The rendering library

The rendering commands of the UI library are finally rendered on the screen. At present, there is a 3D rendering library implemented in pure Go([fauxgl](https://github.com/fogleman/fauxgl)), which can meet the needs when the FPS requirements are not high.
I am going to add support for virtio later so that I can use the acceleration capabilities of the graphics card for rendering.

**Comment by LeapofAzzam-backup** [comment]
You may also use GIO or Shiny for 2D rendering library and https://github.com/aarzilli/nucular (which is a Go port of Nuklear) for the UI library

**Comment by icexin** [comment]
@leapofazzam123 nice project!

**Comment by icexin** [comment]
closed with #32
