### ISSUE TITLE
End goal?

### ISSUE THREAD

**Issue by prologic** [icexin/eggos#12]
I came across your project on one of my feeds… What's your project's end goal? I see some issues you've created which to me seem very complex and large scope of work involved￼

**Comment by icexin** [comment]
Thank you for your attention to this project. I started this project to explore Go's ability to write operating system kernels. Currently it can run most of Go's standard libraries and third-party libraries, so I want to port more capabilities in to make it look more like an operating system :)

In the short term, I plan to port nuklear and fauxgl to support the GUI interface. For more plans, refer to the Roadmap in the README.

In the long-term, I plan to port to my Raspberry Pi to explore the use of go unikernel in the embedded field.

**Comment by prologic** [comment]
Thanks! I'm especially interested in Unikernels and found your project interesting as a way to package services written in Go to run as a virtual machine guest.

**Comment by prologic** [comment]
One question. Do you have a fork/branch of this codebase somewhere that is a minimal viable product in the sense that it has enough to run most/some of the Go runtime and functionality without all the bells 'n whistles you've added since then?

I'm interested in purely what it _took_ to get Go running at all on bare-metal and a minimal viable Go Unikernel.

Do you have a Commit SHA where you _thought_ to yourself, "cool this is working quite well! Now let's add more cool features?"

**Comment by icexin** [comment]
Sorry, but there is currently no branch or commit id that contains the minimum Go runtime code. In fact, most of the driver modules are pluggable, and advanced features (such as js interpreter, nes simulator) are implemented through the code in the `app` directory.

If you want to know how these drivers are initialized, you can look at the code of `kmain/main.go`. The initialization functions inside are used to initialize some drivers. By deleting all these codes, you can directly run ordinary go codes. But functions such as fmt.Println cannot be used.

**Comment by icexin** [comment]
Later I will add more documents to describe how the code works, how to add new drivers, how to implement new syscalls, and how to add new commands.
