### ISSUE TITLE
keep the x86_32 code or not?

### ISSUE THREAD

**Issue by icexin** [icexin/eggos#15]
Eggos will be upgraded to 64-bit in the future. Considering that many codes are strongly related to the architecture, it will be easier to upgrade 64-bit directly without keeping 32-bit code.

However, x86 32-bit protected mode is a classic mode. Many operating system tutorials or materials are based on 32-bit.

If want to keep the 32-bit code, the code needs some refactoring to separate the architecture-related code.

**Comment by icexin** [comment]
Maintaining two archs at the same time at this stage can lead to more complex code, so consider adding `x86_32` back later if needed.

**Comment by astrolox** [comment]
Just wanted to comment that I like the 32 bit support but understand why keeping it makes things harder. So completely support the idea of going purely 64 bit.

Assuming this project stays around for as few years I guess it might be important to have 32 bit for embedded applications. So it also makes sense that you may wish to re add it later.

**Comment by icexin** [comment]
Thank you for your attention to this project. Maintaining multiple architectures is as difficult as the go runtime supporting multiple GOOS and GOARCH. The eggos architecture itself is also being continuously optimized. When the code structure is stabilized, it may not be difficult to support multiple CPU architectures.

**Comment by astrolox** [comment]
Will completing #84 perhaps allow you to restore 32bit?
