### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by JM-299792458** [icexin/eggos#19]
pdet is incomplete : stack allocation disallowed, getting the issue while compiling.

![Screen Shot 2020-10-31 at 2 07 49 PM](https://user-images.githubusercontent.com/39419246/97775011-c1706880-1b82-11eb-9bbe-8a077e0673ea.png)

**Comment by icexin** [comment]
Which go version are you using?

**Comment by JM-299792458** [comment]
1.15

**Comment by JM-299792458** [comment]
okay, got it this build is for 1.13.x and I'm compiling on 1.15.

**Comment by JM-299792458** [comment]
Is there any hack for it, to by pass stack allocation, which I can try ?

**Comment by icexin** [comment]
#4  explains why go1.15 cannot compile.

**Comment by JM-299792458** [comment]
Thank you, got it.
