### ISSUE TITLE
trying to understand linking process

### ISSUE THREAD

**Issue by sauravdeshpande** [icexin/eggos#22]
Osdev.wiki use a linker script, but i could not find one in the repo. I want to understand where have you included the process of the linker, can you please guide me through this part.

Thank you

**Comment by icexin** [comment]
Linker is used in two places, one is to build the multiboot header, see https://github.com/icexin/eggos/blob/f2adf1056fecb7c766cafa68de48a711dd2ba33c/Makefile#L62 
The other place is to build kernel.elf, see https:/ /github.com/icexin/eggos/blob/f2adf1056fecb7c766cafa68de48a711dd2ba33c/Makefile#L57

The reason why linker script is not used is that the virtual address and load address of the kernel are the same, and no complicated logic is needed to change the link process. Another reason is that the go language has its own linker, and it will be more complicated to use the linker script.

**Comment by sauravdeshpande** [comment]
Thank you
