### ISSUE TITLE
Compile error with Go 1.15

### ISSUE THREAD

**Issue by JetSetIlly** [icexin/eggos#4]
Great work. I'm getting compile errors with Go 1.15 though. I've also tested with Go 
1.14.6 and get the same error.

`../../Go/go/pkg/mod/github.com/icexin/netstack@v0.0.0-20201005132454-bd9d0399feb1/sleep/commit_noasm.go:38:45: undefined: preparingG`

Compiling with 1.14.1 and below works fine however so something was introduced between 1.14.1 and 1.14.6 which causes the error.

Compiling with Go 1.13 is fine up to version 1.13.6

**Comment by icexin** [comment]
Sorry but eggos is currently only tested on go1.13.x, the build error of go1.15 is due to netstack restricting the 1.15 build tag.

See https://github.com/icexin/netstack/blob/55fcc16cd0eb096d8418f7bc5162483c31a4e82b/sleep/sleep_unsafe.go#L16

**Comment by xyproto** [comment]
The netstack repository README says:

> NOTE: This repository is no longer maintained. The Netstack code will continue to be updated and maintained as part of gVisor, which now also maintains a branch that is useable with standard Go tools.

Is the plan to move away from `github.com/icexin/netstack`? I assume it's just a leftover from `github.com/google/netstack`.

**Comment by icexin** [comment]
> Is the plan to move away from github.com/icexin/netstack? I assume it's just a leftover from github.com/google/netstack.

My fork did some 386 patch, see https://github.com/icexin/netstack/commit/bd9d0399feb155403a76ebd2defae0da0ea2f918 for details. I will consider migrating to https://github.com/google/gvisor/tree/go later.

Maybe I need to support GOARCH=amd64 first.

**Comment by icexin** [comment]
Fixed via #45
