### ISSUE TITLE
eggos as a library

### ISSUE THREAD

**Issue by icexin** [icexin/eggos#55]
A cool idea, just add one line `import _ "github.com/icexin/eggos`, then every go application can run on bare metal.

**Comment by prologic** [comment]
How would that work at a high-level? 🤔

**Comment by icexin** [comment]
Eggos is divided into two parts from the architecture, one is the kernel code, and the other is the user code. The driver code actually runs in the user mode. The kernel code is responsible for the startup of the go runtime and the implementation of some syscalls that the go runtime depends on. The user code is responsible for the system calls and driver initialization after the go runtime is started. Of course, the real entrance of eggos is actually an ordinary go main function (see kmain/main.go), so some initialization work can be extracted and turned into a package, so that other ordinary go main functions can also run on bare metal .

**Comment by prologic** [comment]
I guess my point was a simply import isn't going to turn your Go application in something that can run on bare metal is it? You still need to do something with the output? Turn it into a QEMU image?

**Comment by prologic** [comment]
Bit like what the guys at [GoKrazy](https://github.com/gokrazy/gokrazy)?

**Comment by icexin** [comment]
I will provide an `egg build` tool to wrap the go build. It will compile the go package into an ELF file compatible with the multiboot specification, and then you can start it with grub or other tools, similar to what `mage multiboot` does. If you want to be simpler, I can provide a command to pack the ELF file and grub into an iso image, just like `mage iso` does.

**Comment by prologic** [comment]
That would be brilliant! If I can just `cd /path/to/my/project` and `eggos build -f iso .` I would totally love that! I've been toying with your project in what little spare time I have, and so far I'm pretty impressed! I wish I had the experience you have with this though, maybe I'l contribute a little in the user space -- I should be able to there 😀

**Comment by icexin** [comment]
closed with https://github.com/icexin/eggos/releases/tag/v0.4.0
