### ISSUE TITLE
cmd/egg: build failure when specifying build path

### ISSUE THREAD

**Issue by prologic** [icexin/eggos#71]
I tried `egg build` on something very simple:

```#!sh
(⎈ |local:default)
prologic@Jamess-iMac
Fri Aug 06 10:16:51
~/tmp/hello-eggos
 130
$ egg build .
2021/08/06 10:16:53 eggos not found in go.mod
2021/08/06 10:16:53 go get github.com/icexin/eggos
go get: added github.com/icexin/eggos v0.4.0
malformed import path "-tags": leading dash
package eggos is not in GOROOT (/usr/local/Cellar/go/1.16/libexec/src/eggos)
2021/08/06 10:18:02 exit status 1
(⎈ |local:default)
prologic@Jamess-iMac
Fri Aug 06 10:18:02
~/tmp/hello-eggos
 1
$ ls -lah
total 2.1M
drwxr-xr-x   6 prologic staff  192 Aug  6 10:18 .
drwxr-xr-x 151 prologic staff 4.8K Aug  6 10:16 ..
-rw-r--r--   1 prologic staff   80 Aug  6 10:18 go.mod
-rw-r--r--   1 prologic staff  98K Aug  6 10:18 go.sum
-rwxr-xr-x   1 prologic staff 2.0M Aug  6 10:16 hello-eggos
-rw-r--r--   1 prologic staff   73 Aug  6 10:16 main.go
(⎈ |local:default)
prologic@Jamess-iMac
Fri Aug 06 10:18:47
~/tmp/hello-eggos
 0
$ cat main.go
package main

import "fmt"

func main() {
	fmt.Println("Hello eggos!")
}
(⎈ |local:default)
prologic@Jamess-iMac
Fri Aug 06 10:18:50
~/tmp/hello-eggos
 0
$ cat go.mod
module hello-eggos

go 1.16

require github.com/icexin/eggos v0.4.0 // indirect
```

It _might_ be the last 3 lines here:

```#!sh
malformed import path "-tags": leading dash
package eggos is not in GOROOT (/usr/local/Cellar/go/1.16/libexec/src/eggos)
2021/08/06 10:18:02 exit status 1
```

Bug?

**Comment by icexin** [comment]
Thanks for the report @prologic 

Remove the current path `.` in the command line, and run `egg build` directly in the project directory. `egg` have bugs when specifying the build path. I will try to fix it.

**Comment by prologic** [comment]
That worked! Quick too!

**Comment by prologic** [comment]
Next question 🤣

How do I use `egg run`?:

```#!sh
(⎈ |local:default)
prologic@Jamess-iMac
Fri Aug 06 12:16:29
~/tmp/hello-eggos
 130
$ ls
go.mod  go.sum  hello-eggos  main.go
(⎈ |local:default)
prologic@Jamess-iMac
Fri Aug 06 12:16:31
~/tmp/hello-eggos
 0
$ egg run ./hello-eggos
2021/08/06 12:16:35 missing kernel file
```

**Comment by icexin** [comment]
The `-k` flag specifies the kernel file. In your example, you can use `egg run -k hello-eggos`

**Comment by prologic** [comment]
Ahh I see! So it's actually a "kernel" that's output. Got it!

**Comment by prologic** [comment]
Why not just make it the argument to `egg run`? e.g: `egg run hello-eggos` ?

**Comment by icexin** [comment]
> Why not just make it the argument to `egg run`? e.g: `egg run hello-eggos` ?

Good suggestion!

**Comment by prologic** [comment]
<img width="1242" alt="Screen Shot 2021-08-06 at 12 39 12" src="https://user-images.githubusercontent.com/1290234/128447726-2c72b41e-e835-4a51-a7f1-f38579156646.png">

it works! 🎉

We _might_ need ways to control qemu options too like running in headless mode, etc...

**Comment by icexin** [comment]
You can specify qemu parameters after `--`, such as `-- -nographic` to make qemu not display the window. 

The complete command is as follows

`egg run -k hello-eggos -- -nographic`

**Comment by prologic** [comment]
I hacked `egg run` a bit to do this:

<img width="1242" alt="Screen Shot 2021-08-06 at 12 57 42" src="https://user-images.githubusercontent.com/1290234/128449365-60b63fa0-2a5f-4ada-b064-d0afdfa3fda6.png">

Basically simplify the usage and take qemu options from `QEMU_OPTS` environment variable so `egg run` options can be egg specific only and not get confuging.

Interesting in a PR for this?

**Comment by icexin** [comment]
> Interesting in a PR for this?

@prologic welcome!

**Comment by prologic** [comment]
We can also borrow some ideas from here: https://github.com/nanovms/ops/tree/master/qemu or reuse some of it's sub-packages.

**Comment by prologic** [comment]
Here is my branch so far https://git.mills.io/prologic/eggos/compare/main...simplify_run_test_qemu_opts

Feel free to comment there or here, I don't publish code to Github anymore 😭

**Comment by icexin** [comment]
> Here is my branch so far https://git.mills.io/prologic/eggos/compare/main...simplify_run_test_qemu_opts

Thanks!

> Feel free to comment there or here, I don't publish code to Github anymore 😭

Sorry to hear that.

> We can also borrow some ideas from here: https://github.com/nanovms/ops/tree/master/qemu or reuse some of it's sub-packages.

Good! At present, the purpose of `egg run` is to verify the correctness of the kernel as a playground, so its feature is relatively simple, and it does not wrap the parameters of qemu too much.

What do you think? @prologic

**Comment by prologic** [comment]
> > Feel free to comment there or here, I don't publish code to Github anymore 😭
> 
> Sorry to hear that.

Yeah it's a long story, but you can read about it [here](https://twtxt.net/blog/prologic/2021/07/11/why-i-no-longer-trust-github) (_if you're curious_).

> > We can also borrow some ideas from here: https://github.com/nanovms/ops/tree/master/qemu or reuse some of it's sub-packages.
> 
> Good! At present, the purpose of `egg run` is to verify the correctness of the kernel as a playground, so its feature is relatively simple, and it does not wrap the parameters of qemu too much.
> 
> What do you think? @prologic

Yeah this is why I _think_ removing the options from `egg run` and `egg run` and putting them behind `QEMU_OPTS` env var makes more sense IHMO. It also simplifies how `egg run` and `egg test` actually work too.

It _might_ (_with more work_) be possible to make `egg run` and `egg test` take no arguments and implicitly to some checks, run build if necessary and just automagically workout what the built kernel is.

**Comment by icexin** [comment]
> It might (with more work) be possible to make egg run and egg test take no arguments and implicitly to some checks, run build if necessary and just automagically workout what the built kernel is.

`egg test` is actually run like this, it will automatically compile the unit test file, and then run it in qemu.

**Comment by prologic** [comment]
Shall I make `egg run` have the same behaviour if no argument is provided?

**Comment by icexin** [comment]
Maybe it is more convenient for `egg run` to not specify parameters, but `egg run` can run ISO file in addition to ELF file. I prefer to explicitly compile kernel with `egg build` and then run the kernel with `egg run`.

Maybe we can let the user explicitly specify the parameters to make `egg run` automatically compile the kernel before running?

**Comment by prologic** [comment]
See https://git.mills.io/prologic/eggos/commit/b303845646c72c4695ac1217af20cbb830e7d3b1

**Comment by prologic** [comment]
This works both ways now 😀

In other words `egg build` and `egg run` are behaving more like `go build` and `go run`.

You can still explicitly build and run with my branch.

**Comment by icexin** [comment]
In fact, it is more complicated to deal with projects without a go.mod file. `egg` will automatically add an `import_eggos.go` file to the project to import eggos when building the project, and at the same time add a dependency on eggos in the `go.mod` file. Therefore `egg build` must be in a project where go.mod exists to compile correctly.

Therefore, `egg run` or `egg build` must build a complete go module project in the temporary directory when processing a single go file to run normally.

**Comment by prologic** [comment]
So I can remove the fallback on the project directory name?

**Comment by prologic** [comment]
Done => https://git.mills.io/prologic/eggos/commit/3ea221543718089a70a02a217d79c64c1f356084

**Comment by icexin** [comment]
Because `egg test` has already compiled the package and has output file, `runKernel` should only run the kernel file, and the part of compiling the kernel can be put into a function separately.

In addition, the code in runTest should look like this
```
runKernel([]string{outfile})
```

**Comment by prologic** [comment]
Good point I'll amend that.

**Comment by prologic** [comment]
Fixed in https://git.mills.io/prologic/eggos/commit/6946e4482d52acc016006b14e05568e791fee7fe

**Comment by icexin** [comment]
@prologic thanks for your contribution. Do you mind if I merge the code into a PR and submit it to GitHub?

**Comment by prologic** [comment]
Absolutely not! I just don't want to host any of my own code (_or forks_) on Github anymore, but I will still be a happy participant of open source 😀 -- Sorry for the _slightly_ extra work though. Btw my Gitea instance accepts Github OAuth in case that's convenience fo ryou.

Also I just tries a simple "Hello World" web server and it works!

```#!sh
$ egg run -p 8000:8000
...
```

<img width="1392" alt="Screen Shot 2021-08-06 at 17 08 49" src="https://user-images.githubusercontent.com/1290234/128471208-5791a4ff-de66-467d-8507-abc118f38779.png">
<img width="1244" alt="Screen Shot 2021-08-06 at 17 08 59" src="https://user-images.githubusercontent.com/1290234/128471225-d361f128-4701-4869-94dd-fc8631fddeab.png">

🎉

**Comment by prologic** [comment]
Next thing I'm going to improve id passing signals (`SIGINT` and `SIGTERM`) from the host where `egg run` is being run to the guest os (egg application).

**Comment by prologic** [comment]
This is pretty amazing shit you've built here btw 😂 I'm loving this! Leet it up! This _may_ very well turn out to be a really really good way of building super secure applications 👌

**Comment by prologic** [comment]
It reminds me of nonovms's ops project just better 🤣

**Comment by prologic** [comment]
=> https://twtxt.net/twt/6qxspia
