### ISSUE TITLE
cycle not allowed

### ISSUE THREAD

**Issue by bitbreakr** [icexin/eggos#86]
Hello,

All commands from the egg executable are not working.

On the root of the cloned project, I for example, trying to run the command:

`shell
./egg run
`

I get this following 

`shell
package github.com/icexin/eggos
	imports github.com/icexin/eggos: import cycle not allowed
2021/08/31 13:42:17 error building kernel: exit status 1
`

I have been trying for all other commands and get the same error as well.

Thanks

**Comment by icexin** [comment]
Thans for your report!

`egg run` should be executed in your own go project directory.  
Each example in the `app/example` directory can be run with `egg run`.

**Comment by mewmew** [comment]
Perhaps this issue can be closed, as the solution was given in https://github.com/icexin/eggos/issues/86#issuecomment-909313706. Or some docs could be added if needed.
